
  name: openboard
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: OpenBoard is a interactive whiteboard application. # 79 char long summary
  description: |
    OpenBoard is an open source cross-platform interactive white board 
    application designed primarily for use in schools. 
    It was originally forked from Open-Sankoré, which was itself based on Uniboard.
    http://openboard.ch/

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
